### ISSUE TITLE
Add instructions about sharing Live Views with teammates

### ISSUE THREAD

**Issue by nserrino** [pixie-io/docs.px.dev#10]
The docs could use more information about how sharing and orgs work in Pixie. For example, if I signed up for Pixie, how can a teammate access the same view in the UI that I am looking at?

**Comment by htroisi** [comment]
[Directions for sharing Live UIs](https://docs.px.dev/about-pixie/faq/#how-do-i-share-a-pixie-dashboard-with-others) can be found in the FAQ.
