### ISSUE TITLE
Add documentation for how to run Pixie on k0s

### ISSUE THREAD

**Issue by nserrino** [pixie-io/docs.px.dev#104]
@soider did a great write-up in the k0s issues for how to set up Pixie on k0s. It involves a few additional steps.

We should
* Add k0s as a supported environment to the Production Environments table in https://docs.px.dev/installing-pixie/requirements/
* Add a new page to https://docs.px.dev/installing-pixie/setting-up-k8s/ for k0s, which should include the extra instructions from https://github.com/k0sproject/k0s/issues/1217 in order to run Pixie on K0s.

Note: The setting up K0s should link to the Install Pixie guide, not replicate the instructions to install Pixie.

Additionally, we should note that the instructions provided by the docs are partially setting up Pixie on K0s in a development, single-mode environment. However, the same following steps should apply to other K0s environments.

**Comment by htroisi** [comment]
"Setting up K0s with Pixie" reference docs are now available here: https://docs.px.dev/installing-pixie/setting-up-k8s/k0s-setup/
