### ISSUE TITLE
Add reference docs for px.Display()

### ISSUE THREAD

**Issue by npreiser** [pixie-io/docs.px.dev#105]
Also please add the structure of what a "table" is .

**Comment by htroisi** [comment]
Hi @npreiser - Here's where you can learn more about these concepts:
- ["Writing your first PxL script"](https://docs.px.dev/tutorials/pxl-scripts/write-pxl-scripts/custom-pxl-scripts-1) tutorial
- [DataFrame reference docs](https://docs.px.dev/reference/pxl/operators/dataframe.dataframe/)
- [px.display reference docs](https://docs.px.dev/reference/pxl/operators/px.display/)
