### ISSUE TITLE
"px/demo_script" has been prune

### ISSUE THREAD

**Issue by vincent-pli** [pixie-io/docs.px.dev#137]
The folder `pixie/src/pxl_scripts/px/demo_script` has been remove by the [commit](https://github.com/pixie-io/pixie/commit/c93ad29887556d7f4be46e5ae60602661d3c616a#diff-a5989186bee83d838c080cce53f23209dc211423c9610d375a4b3f8eb3f97b12)

but we still use it in the tutorials:
```
./content/en/02-installing-pixie/03-install-guides/01-community-cloud-for-pixie.md:px run px/demo_script
./content/en/02-installing-pixie/03-install-guides/01-community-cloud-for-pixie.md:3. Now, select a script, e.g. `px/demo_script` or `px/http_data`.
./content/en/04-tutorials/02-pxl-scripts/02-script-dev-environment.md:cp -r px/demo_script px/my_pxl_script
```
To replace it, I suggest to adopt https://github.com/pixie-io/pixie/tree/main/src/pxl_scripts/px/http_post_requests
since it's very straight forward for a begginer.

**Comment by htroisi** [comment]
@vincent-pli - thanks for taking the time to report this! I'll create a PR to get those mentions of px/demo script removed.
