### ISSUE TITLE
chromium rendering overflows

### ISSUE THREAD

**Issue by bdols** [pixie-io/docs.px.dev#165]
**Describe the bug**
The sidebar anchored on the right overflows out of the bound of the browser's window and scrollbar, so far I have seen this in Vivaldi, and Microsoft Edge which leads me to believe that rendering isn't broken in just my preferred browser.

**To Reproduce**
1. Go to https://docs.pixielabs.ai/installing-pixie/install-guides/#3.-install-the-pixie-cli
2. resize canvas to 1614x1289
3. See that "invite others to your organization (optional)" overflows over the scroll bar and maybe even the browser window.

**Expected behavior**

renders correctly

**Screenshots**
![pixie_overflow_1614x1289](https://user-images.githubusercontent.com/286836/162470415-3963ef6d-3b91-432e-bed0-3f74a47d650e.png)

**Additional context**

I also have found that keyboard navigation (i.e. pressing space bar to scroll down) doesn't work on the pixie doc site.

**Environment**

**Comment by NickLanam** [comment]
Noteworthy: In Firefox (Gecko), it instead word wraps with no indentation:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/314133/172239216-ac946806-ebce-4fd1-aee4-728c607d4524.png">

This sidebar is just a `div` full of `a` tags. A positive left margin and a negative `text-indent` on the `a` tags themselves, as well as fixing the container's dimensions, should be enough to fix both browsers.

EDIT: The numbering in this example is part of the headings themselves, so there may need to be some care taken there.
