### ISSUE TITLE
Loop in redirect: deploy options

### ISSUE THREAD

**Issue by bdronneau** [pixie-io/docs.px.dev#174]
**Describe the bug**
Hello,

When reaching https://docs.pixielabs.ai/reference/admin/deploy-options/ I have a redirect to https://docs.pixielabs.ai/reference/admin/deploy-options and vice versa.

**To Reproduce**
1. Go to https://docs.pixielabs.ai/reference/admin/deploy-options/
2. Enjoy redirect loop

**Expected behavior**

Only one redirect with the trailing slash

**Screenshots**
N/A

**Additional context**
N/A

**Environment**

Tested on Chromium under private mode

**Comment by bdronneau** [comment]
Hi,

Fix seems to be in main but not deploy for now ?

**Comment by htroisi** [comment]
Should be deployed on prod now.
