### ISSUE TITLE
Support keyboard navigation (space bar, down arrow key) 

### ISSUE THREAD

**Issue by htroisi** [pixie-io/docs.px.dev#186]
Most websites offer this interaction and we should support this too:
- pressing the space bar to scroll down by one page
- pressing the down arrow key to scroll down an arbitrary amount

**Comment by NickLanam** [comment]
After doing a little initial poking around, it seems that the element `#gatsby-focus-wrapper` is a parent of the scroll container and eats the keyboard events before they can do what they're supposed to do.

This seems to be a known issue with Gatsby: https://github.com/gatsbyjs/gatsby/issues/29037
But there are workarounds there that we can try.
