### ISSUE TITLE
Missing functions in the UDF overview page

### ISSUE THREAD

**Issue by philkuz** [pixie-io/docs.px.dev#194]
**Describe the bug**
The UDF overview page is missing certain functions that are available in the sidebar. I was trying to find time_to_int64 and couldn't use cmd+f on the page because it literally was not there. 
https://docs.px.dev/reference/pxl/udf/
However the page does exist: 
https://docs.px.dev/reference/pxl/udf/int64_to_time/
**To Reproduce**
1. Open https://docs.px.dev/reference/pxl/udf/
2. cmd+f time_to_int64 and see that you don't get any results on the page.
**Expected behavior**
the time_to_int64 function should be rendered on the page. Any updates to UDFs should be rendered on this page.

**Screenshots**

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/5456019/173960974-09284166-bc3a-49de-94b1-1124c5c2646c.png">
**Additional context**

**Comment by htroisi** [comment]
@philkuz - looks like you fixed this in https://phab.corp.pixielabs.ai/D11600?

**Comment by htroisi** [comment]
This was fixed by [this action](https://github.com/pixie-io/docs.px.dev/pull/189#issuecomment-1159233080).
