### ISSUE TITLE
Alert rendered incorrectly in Self-Hosted Install Guide

### ISSUE THREAD

**Issue by philkuz** [pixie-io/docs.px.dev#246]
https://docs.px.dev/installing-pixie/install-guides/self-hosted-pixie/#1.-deploy-pixie-cloud-authentication-using-kratos-hydra
![image](https://user-images.githubusercontent.com/5456019/203448844-41cdd665-0ef3-4e38-9e3e-1198e64954a7.png)
is rendered as code box instead of as an alert box.
Should be an alert box

**Comment by htroisi** [comment]
Fixed by https://github.com/pixie-io/docs.px.dev/pull/244. That PR just hadn't been pushed to prod yet.
