### ISSUE TITLE
install pixie through  helm with self-hosting Pixie Cloud

### ISSUE THREAD

**Issue by andriipetruk** [pixie-io/docs.px.dev#248]
Hi,

page - https://docs.px.dev/installing-pixie/install-schemes/helm/

-helm install pixie pixie-operator/pixie-operator-chart --set deployKey=<deploy-key-goes-here> --set clusterName=<cluster-name> --namespace pl --create-namespace --set devCloudNamespace plc
+helm install pixie pixie-operator/pixie-operator-chart --set deployKey=<deploy-key-goes-here> --set clusterName=<cluster-name> --namespace pl --create-namespace --set devCloudNamespace=plc

missed "=" after param key "devCloudNamespace"

**Comment by htroisi** [comment]
@andriipetruk thanks for taking the time to report this!
